print("SJC23MCA-2017 : ANNA S")
print("Batch : MCA 2023-25")

import numpy as np;
arr_id=np.array([1,2,3,4,5])
diagonal_matrix=np.diag(arr_id)
print("1D Array:")
print(arr_id)
print("Diagonal Matrix:")
print(diagonal_matrix)
arr_2d_square=np.array([[1,2,3],[4,5,6],[7,8,9]])
diagonal_elements=np.diag(arr_2d_square)
print("2D Square Matrix:")
print(arr_2d_square)
print("Diagonal Elements:")
print(diagonal_matrix)
arr_2d_non_square=np.array([[1,2,3],[4,5,6]])
diagonal_elements_non_square=np.diag(arr_2d_non_square)
print("2D Non-Square Matrix:")
print(arr_2d_non_square)
print("Diagonal Elements(Non-square):")
print(diagonal_elements_non_square)